### ISSUE TITLE
DFLib / Parquet and Avro classpath issues

### ISSUE THREAD

**Issue by andrus** [dflib/jjava#30]
Another classpath issue potentially related to Ivy. We can't work with Parquet or Avro APIs. It works well in a standalone Java app, as well as in JShell (with `/env --class-path` taken from the Java app). But in Jupyter (jjava M2) the code fails with `NoClassDefFoundError`.

I vaguely remember this happening with Avro back in the iJava days as well, though we ignored it cause we could not do anything about it.

## Parquet

```java
%maven org.dflib:dflib-jupyter:1.0.0-SNAPSHOT

// the error is the same with or without this dependency
// %maven com.fasterxml.woodstox:woodstox-core:5.4.0

import org.dflib.parquet.*;

Parquet.loader().load("some.parquet");
```

```
java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
	at org.apache.parquet.conf.HadoopParquetConfiguration.<init>(HadoopParquetConfiguration.java:39)
	at org.apache.parquet.conf.HadoopParquetConfiguration.<init>(HadoopParquetConfiguration.java:35)
	at org.apache.parquet.hadoop.ParquetReader$Builder.<init>(ParquetReader.java:236)
	at org.dflib.parquet.read.DataframeParquetReaderBuilder.<init>(DataframeParquetReaderBuilder.java:10)
	at org.dflib.parquet.ParquetLoader.load(ParquetLoader.java:48)
	at org.dflib.parquet.ParquetLoader.load(ParquetLoader.java:28)
	at org.dflib.parquet.ParquetLoader.load(ParquetLoader.java:32)
	at .(#24:1)
```

## Avro

```java
Avro.loader().load("some.avro")
```

```
java.lang.NoClassDefFoundError: org/apache/avro/LogicalTypes$LogicalTypeFactory
	at .(#21:1)
```

**Comment by stariy95** [comment]
`com.fasterxml.woodstox:woodstox-core:5.4.0` artifact has a `bundle` type, and we filter out everything that is not `jar`, need to check Avro if it's the same problem

**Comment by stariy95** [comment]
Avro and Parquet working fine now

**Comment by andrus** [comment]
Nice! Looking forward to M3
